/**
 * 页面业务说明字典（新人友好）
 *
 * key   = 路由 name（见 router/routes.ts）
 * value = 一句话业务说明，回答「这个页面是干嘛的」
 *
 * 用途：侧边菜单 hover 提示、全局搜索结果说明、模块导航页。
 * 维护约定：新增业务页面时，在此补一条说明；说明要讲“用来做什么”，不要复述标题。
 */
export const PAGE_DESCRIPTIONS: Record<string, string> = {
  // ===== 核心 / 首页与工作台 =====
  Portal: '机构经营与安全总览，管理者的第一落脚点',
  FunctionMap: '全站功能目录，按业务板块查“哪个页面干什么”',
  Workbench: '个人待办中心：打卡、待办、审批、日程集中处理',
  WorkbenchOverview: '我的当日待办、审批与协同事项一屏处理',
  WorkbenchTodo: '待我处理的任务清单',
  WorkbenchMyInfo: '我的个人档案与账号信息',
  WorkbenchAttendance: '我的打卡、考勤与请假申请',
  WorkbenchSchedule: '我的排班与日程安排',
  WorkbenchReports: '我的日报/周报/月报总结',
  WorkbenchApprovals: '待我审批的单据',

  // ===== 长者管理 =====
  Elder: '长者档案、在院状态与服务全生命周期管理',
  ElderInHospitalOverview: '单个长者的护理/膳食/医疗/费用一体化视图',
  ElderBedPanorama: '楼栋-楼层-房间-床位的可视化床态总览',
  ElderList: '长者档案总表：查询、建档与集中操作',
  ElderAssessment: '长者能力与各类量表评估的管理入口',
  ElderAssessmentAdmission: '入住时的能力初评',
  ElderAssessmentRegistration: '评估任务登记与分配',
  ElderAssessmentContinuous: '在院期间的周期性复评',
  ElderAssessmentArchive: '历史评估记录归档查询',
  ElderAssessmentOtherScale: '跌倒、压疮等其他专项量表评估',
  ElderAssessmentCognitive: '认知（如痴呆）能力评估',
  ElderAssessmentSelfCare: '日常自理能力（ADL）评估',
  ElderContractsInvoices: '长者合同与票据查询',
  ElderAdmissionProcessing: '办理入住：分床、押金、合同与二维码',
  ElderStatusChangeCenter: '外出、试住、退住、离院等状态变更总入口',
  ElderStatusChangeOverview: '长者状态变更的汇总看板',
  ElderStatusChangeOuting: '长者请假外出登记',
  ElderStatusChangeVisitRegister: '家属/访客来访登记',
  ElderStatusChangeDischargeApply: '发起退住申请',
  ElderStatusChangeTrialStay: '短期试住登记',
  ElderStatusChangeMedicalOuting: '外出就医登记与跟踪',
  ElderStatusChangeDeathRegister: '死亡登记与后续流程',
  ElderStatusChangeDischargeSettlement: '退住时的费用结算',

  // ===== 营销管理 =====
  Marketing: '从线索到签约入住的销售全流程管理',
  MarketingWorkbench: '销售当日待办、风险与转化一屏总览',
  MarketingLeads: '客户线索的分类与集中管理',
  MarketingLeadsAll: '全部客户线索',
  MarketingLeadsIntent: '有意向的重点客户',
  MarketingLeadsInvalid: '已失效/无效客户',
  MarketingLeadsBlacklist: '黑名单客户处置与恢复',
  MarketingLeadsUnknownSource: '缺失来源渠道的线索补全',
  MarketingLeadsMedicalTransfer: '医护模块流入的潜在客户',
  MarketingInteractions: '销售跟进与回访记录中心',
  MarketingFollowupRecords: '跟进/回访轨迹记录',
  MarketingFollowupDue: '待执行的回访任务',
  MarketingFollowupToday: '今日需完成的跟进',
  MarketingFollowupOverdue: '逾期未跟进的风险客户',
  MarketingFunnel: '按阶段推进线索的销售漏斗',
  MarketingFunnelConsultation: '咨询阶段线索池',
  MarketingFunnelEvaluation: '评估阶段高意向客户',
  MarketingFunnelSigning: '待签约合同推进',
  MarketingFunnelAdmission: '待办理入住的合同',
  MarketingFunnelLost: '流失客户归因与二次激活',
  MarketingReservation: '床位预定与锁床、床态联动',
  MarketingReservationRecords: '床位预定记录',
  MarketingReservationLock: '锁床客户与状态跟踪',
  MarketingReservationExpiring: '锁床/预定临期预警',
  MarketingReservationPanorama: '销售视角的床态全景',
  MarketingContracts: '合同签署、续签与变更管理',
  MarketingContractsPending: '待签署合同处理',
  MarketingContractsSigned: '已签合同查询与协同',
  MarketingContractsRenewal: '合同续签到期提醒',
  MarketingContractsChange: '合同条款变更',
  MarketingContractsAttachments: '合同附件管理',
  MarketingCallback: '签约后各阶段回访管理',
  MarketingCallbackCheckin: '入住后回访',
  MarketingCallbackTrial: '试住客户回访',
  MarketingCallbackDischarge: '退住客户回访与原因沉淀',
  MarketingCallbackScore: '回访质量评分',
  MarketingReports: '销售转化、渠道与业绩报表',
  MarketingReportConversion: '各阶段转化率统计',
  MarketingReportConsultation: '咨询量统计',
  MarketingReportUnknownChannel: '不明渠道线索统计',
  MarketingReportFollowup: '跟进情况统计',
  MarketingReportCallback: '回访情况统计',
  MarketingReportChannel: '渠道效果评估',
  MarketingReportSalesPerformance: '销售人员业绩',
  MarketingReportChannelRank: '渠道贡献排名',
  MarketingReportSnapshots: '经营快照留档',
  MarketingPlan: '营销方案制定与审批',

  // ===== 后勤保障 =====
  Logistics: '资产、物资、餐饮、维修一体化后勤运营',
  LogisticsWorkbench: '后勤当日风险、任务与指标总览',
  LogisticsTaskCenter: '后勤任务的接单与闭环处理',
  LogisticsAssets: '楼栋/房间/床位等资产与床态管理',
  LogisticsRoomStateMap: '按楼层平面的房态图',
  LogisticsBedManagement: '床位增删改与状态维护',
  LogisticsBedTypeConfig: '床位类型基础配置',
  LogisticsRoomTypeConfig: '房间类型基础配置',
  LogisticsAreaConfig: '楼栋区域划分配置',
  LogisticsBedStatusRecord: '床位状态变更记录',
  LogisticsCleaningRecord: '房间清洁消杀记录',
  LogisticsMaintenanceRecord: '设施维修记录',
  LogisticsStorage: '物资采购、出入库与库存管理',
  LogisticsWarehouse: '仓库基础设置',
  LogisticsSupplier: '供应商档案',
  LogisticsPurchase: '物资采购单',
  LogisticsInbound: '物资入库',
  LogisticsOutbound: '物资出库/领用',
  LogisticsTransfer: '仓库间物资调拨',
  LogisticsStockQuery: '实时库存查询',
  LogisticsAlerts: '低库存/临期预警',
  LogisticsStockCheck: '库存盘点',
  LogisticsStockAmount: '库存金额统计',
  LogisticsDining: '菜品、食谱、点餐与送餐管理',
  LogisticsDiningDish: '菜品档案',
  LogisticsDiningRecipe: '周期食谱编排',
  LogisticsDiningOrder: '长者个性化点餐',
  LogisticsDiningStats: '订餐数据统计',
  LogisticsDiningProcurementPlan: '餐饮采购计划',
  LogisticsDiningPrepZone: '按区备餐安排',
  LogisticsDiningDeliveryArea: '送餐区域划分',
  LogisticsDiningDeliveryPlan: '送餐计划编排',
  LogisticsMaintenance: '报修、派单与维修进度',
  LogisticsMaintenanceCost: '维修成本记录',
  LogisticsMaintenanceAssets: '设备档案台账',
  LogisticsReports: '床位、库存、采购、餐饮等后勤报表',
  LogisticsReportMaintenanceTodoLog: '维保待办执行日志',
  LogisticsCommerce: '内部商城商品与订单管理',
  LogisticsCommerceCategory: '商品大类',
  LogisticsCommerceTag: '商品标签',
  LogisticsCommerceRisk: '商品禁忌规则',
  LogisticsCommerceProduct: '商品信息维护',
  LogisticsCommerceOrder: '商城订单',
  LogisticsCommercePoints: '积分账户',

  // ===== 照护管理（护理团队） =====
  CareStaff: '护工/护理人员与小组管理',
  CaregiverInfo: '护工档案与用工信息',
  CaregiverGroups: '护工分组',
  CareService: '护理服务项目、等级与计划',
  CareServiceItems: '可提供的护理服务项目',
  CareLevels: '护理等级定义',
  ServicePlans: '长者护理服务计划',
  CareNursingReports: '护理执行报表',
  CareNursingRecords: '护理执行记录',
  ServiceBookings: '护理服务预约',
  CareScheduling: '护理排班管理',
  ShiftTemplates: '排班方案模板',
  CareShiftCalendar: '护理排班日历',
  ShiftHandovers: '交接班',
  CareToday: '护理今日任务',
  CareTemplate: '护理任务模板',

  // ===== 财务运营中心 =====
  Finance: '收费、账单、对账与经营分析中心',
  FinanceWorkbench: '财务当日收费、欠费、对账重点一屏',
  FinancePayments: '收银、收费登记与收款流水',
  FinancePaymentsCashierDesk: '当面收款、开票、打印小票',
  FinancePaymentsRegister: '收费项目登记',
  FinancePaymentsRecords: '收款流水查询',
  FinancePaymentsInvoice: '发票与收据管理',
  FinancePaymentsRefundReversal: '退款与收款冲正',
  FinancePaymentsShiftClose: '收银日结与交班',
  FinanceBilling: '长者账单与账户管理',
  FinanceBillsInAdmission: '入住时产生的账单',
  FinanceBillsInResident: '在住周期账单',
  FinanceBillsDetailQuery: '账单明细查询',
  FinanceAccountsList: '长者预存账户列表',
  FinanceAccountsLedger: '账户资金流水',
  FinancePrepaidRecharge: '账户预存充值',
  FinanceAccountsWarningRules: '账户余额预警规则',
  FinanceAdmissionFeeAudit: '入住费用审核',
  FinanceSources: '各类消费与费用分摊来源',
  FinanceFlowsConsumption: '长者消费登记',
  FinanceFlowsMedical: '医护费用流水',
  FinanceFlowsMedicalErrors: '医护费用异常处理',
  FinanceFlowsDining: '餐饮扣费流水',
  FinanceFlowsLogistics: '物资/后勤收费流水',
  FinanceFlowsAdjustments: '费用调整单',
  FinanceAllocationPublicCost: '公共费用计算',
  FinanceAllocationTasks: '费用分摊入账任务',
  FinanceRisk: '欠费催缴与费用异常处理',
  FinanceBillsFollowUp: '欠费催缴跟进',
  FinanceBillsAutoDeduct: '自动扣费与催缴',
  FinanceBillsAutoDeductErrors: '自动扣费异常',
  FinanceReconcileException: '对账异常处理',
  FinanceReconcileLedgerHealth: '财务数据一致性巡检',
  FinanceReconcileIssueCenter: '财务异常集中修复',
  FinanceDischarge: '退住结算与月结',
  FinanceDischargeReview: '退住费用审核',
  FinanceDischargeSettlementCenter: '退住结算办理',
  FinanceDischargePrintSign: '结算单打印签字',
  FinanceDischargeStatusSync: '结算状态回写',
  FinanceReconcileCenter: '对账中心',
  FinanceReconcileInvoice: '发票对账',
  FinanceReconcileMonthClose: '月结进度跟踪',
  FinanceReports: '收支、营收结构等经营分析',
  FinanceReportsOverall: '总收支报表',
  FinanceReportsRevenueStructure: '营收结构分析',
  FinanceReportsFloorRoom: '楼层/房间收支',
  FinanceReportsRoomOpsDetail: '房间经营详情',
  FinanceReportsOccupancyConsumption: '入住与消费关联分析',
  FinanceReportsMonthlyOps: '机构月度运营',
  FinanceConfig: '费用科目、计费与审批规则配置',
  FinanceConfigMasterData: '财务主数据配置',
  FinanceConfigFeeSubjects: '费用科目设置',
  FinanceBillsRules: '计费规则配置',
  FinanceAllocationRules: '费用分摊规则',
  FinanceConfigPaymentChannels: '支付渠道配置',
  FinanceConfigApprovalFlow: '财务审批流与权限',
  FinanceConfigChangeLog: '配置变更记录',

  // ===== 医护健康服务 =====
  HealthMedication: '药品缴存、用药登记与设置',
  HealthDrugDictionary: '药品字典',
  HealthDrugDeposit: '长者药品缴存',
  HealthMedicationSetting: '用药规则设置',
  HealthMedicationRegistration: '用药执行登记',
  HealthMedicationRemaining: '剩余药量跟踪',
  HealthManagement: '健康档案、数据与巡检',
  HealthArchive: '长者健康档案',
  HealthData: '生命体征等健康数据',
  HealthInspection: '健康巡检',
  HealthNursingLog: '护理日志',
  MedicalCare: '医护照护一体化服务与风险管理',
  MedicalCareCenter: '医护服务导航中心',
  MedicalCareResidentList: '长者/患者列表',
  MedicalCareResidentDiseases: '长者基础疾病维护',
  MedicalCareTaskBoard: '护理任务看板',
  MedicalCareUnifiedTaskCenter: '医护统一任务中心',
  MedicalCareInspection: '健康巡检',
  MedicalCareMedicationRegistration: '用药登记',
  MedicalCareNursingLog: '护理日志',
  MedicalCareHandovers: '医护交接班',
  MedicalCareTcmAssessment: '中医体质评估',
  MedicalCareCvdAssessment: '心血管风险评估',
  MedicalCareIntegratedAccount: '健康服务与医护账户一体化',
  MedicalCareOrders: '医嘱开立与管理',
  MedicalCareNursingQuality: '护理质量管理中心',
  MedicalCareAlertRules: '健康异常规则配置',
  MedicalCareSmartAlerts: '智慧设备告警',
  MedicalCareSmartRules: '安全场景告警规则',
  MedicalCareSmartDispatch: '告警派单看板',
  MedicalCareEmr: '电子病历',
  MedicalCareOrderExecutions: '医嘱执行记录',
  MedicalCarePharmacy: '药事管理',
  MedicalCareAiReports: 'AI 健康评估报告',

  // ===== 消防安全 =====
  FireSafety: '消防设施、值班巡查与维保管理',
  FireFacilityManagement: '消防设施台账',
  FireControlRoomDuty: '控制室值班记录',
  FireMonthlyCheck: '每月防火检查',
  FireDayPatrol: '日间防火巡查',
  FireNightPatrol: '夜间防火巡查',
  FireMaintenanceReport: '消防设施维保报告',
  FireFaultMaintenance: '消防设施故障维护',
  FireDataStats: '消防数据统计',

  // ===== 长护险与监管 =====
  Ltci: '长期护理保险与政府监管上报',
  LtciAssessments: '失能等级评估',
  LtciBenefits: '长护险待遇管理',
  LtciSettlements: '长护险结算',
  GovReportTasks: '监管数据上报任务',
  GovReportChannels: '上报渠道配置',

  // ===== 统计分析 =====
  Stats: '入住、消费、经营等多维统计分析',
  StatsCheckIn: '入住/离院趋势统计',
  StatsConsumption: '长者消费分析',
  StatsElderInfo: '长者结构与护理等级分布',
  StatsOrg: '机构维度综合统计',
  StatsOrgMonthlyOperation: '机构月运营详情',
  StatsOrgElderFlow: '机构老人出入统计',
  StatsOrgBedUsage: '床位使用率统计',
  StatsMonthlyRevenue: '月度运营收入统计',
  StatsOperationsDashboard: '管理驾驶舱：跨模块经营总览',
  StatsExecutiveCockpit: '经营驾驶舱：院长决策视图',
  StatsSensitiveAccessAudit: '敏感数据访问审计',
  StatsElderFlowReport: '老人出入院明细报表',

  // ===== 一卡通 / 生活服务 =====
  CardAccount: '一卡通卡务管理',
  CardRecharge: '一卡通充值记录',
  CardConsume: '一卡通消费记录',
  LifeBirthday: '会员生日提醒',
  LifeMealPlan: '膳食计划',
  LifeActivity: '活动组织管理',
  LifeIncident: '事故/事件登记',
  LifeHealthBasic: '基础健康记录',
  LifeRoomCleaning: '房间打扫记录',
  LifeMaintenance: '生活设施维修',

  // ===== 行政管理 OA =====
  OA: '协同办公、家属服务与行政事务',
  OaOverview: '行政业务导航中心',
  OaFamilyService: '家属服务与账号中心',
  OaFamilyUsers: '家属账号与绑定',
  OaWorkExecution: '协同办公与任务执行',
  OaTask: '行政任务管理',
  OaFamilyCommunication: '家属反馈与沟通',
  OaDailyReport: '日总结',
  OaWeeklyReport: '周总结',
  OaMonthlyReport: '月总结',
  OaYearlyReport: '年总结',
  OaLife: '生日、打扫、维修等生活服务',
  OaCard: '一卡通管理',
  OaKnowledge: '知识库',
  OaNotice: '通知公告发布',
  OaActivityCenter: '活动组织与满意度调查',
  OaActivityCenterPlan: '活动计划',
  OaActivityCenterRecords: '活动执行记录',
  OaActivityCenterSurveyManage: '满意度调查管理',
  OaActivityCenterSurveyStats: '满意度调查统计',
  OaApproval: '行政审批中心',
  OaDocument: '文档中心',

  // ===== 人力资源 =====
  Hr: '招聘、档案、考勤、薪酬与绩效激励',
  HrOverview: '人力资源业务导航中心',
  HrRecruitment: '招聘需求与办理',
  HrRecruitmentNeeds: '招聘办理台',
  HrProfileCenter: '员工档案管理',
  HrProfileOnboarding: '员工入职向导',
  HrProfileBasic: '员工基本信息',
  HrProfileContracts: '劳动合同管理',
  HrProfileAccountAccess: '员工账号与领导设置',
  HrProfileContractTemplates: '合同模板库',
  HrProfileContractPrint: '合同打印',
  HrProfileCertificates: '员工证书上传',
  HrProfileAttachments: '档案附件',
  HrProfileContractReminders: '合同到期提醒',
  HrProfileSocialSecurityReminders: '社保到期/未办理提醒',
  HrAttendance: '考勤、排班与班组',
  HrAttendanceSchemes: '排班方案',
  HrAttendanceGroups: '班组设置',
  HrAttendanceCalendar: '排班日历',
  HrAttendanceLeaveApproval: '请假审批',
  HrAttendanceRecords: '考勤记录',
  HrAttendanceAbnormal: '考勤异常处理',
  HrAttendanceAccessControl: '门禁系统对接',
  HrAttendanceCardSync: '一卡通考勤对接',
  HrCompliance: '规章制度与合规',
  HrCompliancePolicies: '规章制度库',
  HrCompliancePolicyAlerts: '制度更新预警',
  HrExpense: '薪酬、报销与员工费用',
  HrExpenseDormitory: '员工宿舍管理',
  HrExpenseApprovalFlow: '报销审批流',
  HrDevelopment: '培训与证书发展',
  HrDevelopmentRecords: '培训记录',
  HrDevelopmentCertificates: '证书管理',
  HrDevelopmentCertificateReminders: '证书到期提醒',
  HrPerformanceCenter: '绩效考核管理',
  HrPerformanceReports: '绩效报表',
  HrPerformanceRewardPunishment: '奖惩记录',
  HrIncentive: '员工积分激励',
  HrIncentiveLedger: '积分台账',
  HrIncentiveRules: '积分规则',

  // ===== 基础数据配置 =====
  BaseConfig: '各业务下拉项与基础字典配置',
  BaseConfigElderType: '老人类别字典',
  BaseConfigMarketing: '营销相关基础字典',
  BaseConfigMarketingCustomerTag: '客户标签字典',
  BaseConfigMarketingSourceChannel: '来源渠道字典',
  BaseConfigAssessment: '评估相关配置',
  BaseConfigResidence: '入住相关配置',
  BaseConfigResidenceBedType: '床位类型字典',
  BaseConfigResidenceRoomType: '房间类型字典',
  BaseConfigResidenceAreaSettings: '区域设置',
  BaseConfigActivity: '活动相关配置',
  BaseConfigCommunity: '社区/后勤相关配置',
  BaseConfigCommunityMaintenanceCategory: '维修分类字典',
  BaseConfigCommunityTaskTypeSettings: '任务类型设置',
  BaseConfigDischargeFeeSettings: '退住费用设置',
  BaseConfigFee: '费用相关配置',
  BaseConfigRefundReason: '退款原因字典',
  BaseConfigTrialPackage: '试住套餐配置',

  // ===== 系统管理 =====
  System: '官网、机构信息、角色与部门管理',
  SystemSiteConfigCenter: '官网内容配置',
  SystemOrgInfo: '机构基础信息',
  SystemRoleManage: '角色与权限管理',
  SystemDepartmentManage: '部门管理'
}

/**
 * 全局搜索别名：口语/同义词 → 命中该路由 name
 * 让新人用大白话也能搜到页面（如“收钱”→收银台）。
 */
export const PAGE_ALIASES: Record<string, string[]> = {
  FinancePaymentsCashierDesk: ['收钱', '收款', '结账', '开票'],
  FinanceBillsFollowUp: ['催费', '要钱', '欠钱', '催缴'],
  ElderBedPanorama: ['找床', '床位图', '空床'],
  LogisticsRoomStateMap: ['房间图', '房态'],
  ElderAdmissionProcessing: ['入住', '办入院', '安排床位'],
  ElderStatusChangeDischargeApply: ['退住', '退院', '离院'],
  WorkbenchAttendance: ['打卡', '请假', '考勤'],
  WorkbenchTodo: ['待办', '任务'],
  WorkbenchApprovals: ['审批', '批单'],
  MarketingLeadsAll: ['客户', '线索', '意向'],
  HealthMedicationRegistration: ['喂药', '吃药', '发药'],
  MedicalCareInspection: ['巡检', '查房'],
  LifeBirthday: ['生日', '过生日'],
  HrProfileOnboarding: ['入职', '新员工'],
  MedicalCareOrders: ['医嘱', '开药'],
  ElderList: ['老人', '长者', '住户'],
  FinancePaymentsInvoice: ['发票', '收据'],
  LogisticsMaintenance: ['报修', '修东西', '坏了']
}

/** 取页面业务说明；无则返回空串 */
export function getPageDescription(routeName?: string | null): string {
  if (!routeName) return ''
  return PAGE_DESCRIPTIONS[routeName] || ''
}

/** 取页面搜索别名；无则返回空数组 */
export function getPageAliases(routeName?: string | null): string[] {
  if (!routeName) return []
  return PAGE_ALIASES[routeName] || []
}
