-- 医养结合收口：巡诊排班 / 慢病随访 / 120急救对接（H2 测试库）
CREATE TABLE medical_rounds_plan (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  plan_date DATE NOT NULL,
  time_slot VARCHAR(32),
  doctor_id BIGINT,
  doctor_name VARCHAR(60),
  area VARCHAR(120),
  elder_scope VARCHAR(16) NOT NULL DEFAULT 'AREA',
  elder_ids_json VARCHAR(2000),
  status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE medical_rounds_record (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  plan_id BIGINT,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64),
  round_time DATETIME,
  findings VARCHAR(1000),
  handle_opinion VARCHAR(1000),
  result_level VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
  emr_record_id BIGINT,
  medical_order_id BIGINT,
  doctor_id BIGINT,
  doctor_name VARCHAR(60),
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE medical_followup_plan (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64),
  disease_type VARCHAR(32) NOT NULL DEFAULT 'HYPERTENSION',
  plan_name VARCHAR(120),
  frequency_days INT NOT NULL DEFAULT 30,
  target_indicators VARCHAR(1000),
  next_followup_date DATE,
  last_followup_date DATE,
  doctor_id BIGINT,
  doctor_name VARCHAR(60),
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE medical_followup_record (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64),
  followup_date DATE NOT NULL,
  vital_json VARCHAR(1000),
  health_data_id BIGINT,
  medication_compliance VARCHAR(16),
  assessment_level VARCHAR(16) NOT NULL DEFAULT 'CONTROLLED',
  assessment VARCHAR(1000),
  next_followup_date DATE,
  doctor_id BIGINT,
  doctor_name VARCHAR(60),
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE medical_emergency_event (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64),
  alert_id BIGINT,
  event_time DATETIME NOT NULL,
  location VARCHAR(200),
  symptom VARCHAR(500),
  call_time DATETIME,
  call_operator_id BIGINT,
  call_operator_name VARCHAR(60),
  hospital_name VARCHAR(120),
  escort_name VARCHAR(60),
  depart_time DATETIME,
  outcome VARCHAR(16),
  outcome_time DATETIME,
  outcome_note VARCHAR(500),
  reporter_id BIGINT,
  reporter_name VARCHAR(60),
  status VARCHAR(16) NOT NULL DEFAULT 'INITIATED',
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE medical_rescue_record (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT,
  org_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  elder_id BIGINT,
  timeline_json VARCHAR(4000),
  participants VARCHAR(500),
  drugs_used VARCHAR(500),
  measures VARCHAR(1000),
  result VARCHAR(16),
  result_note VARCHAR(500),
  start_time DATETIME,
  end_time DATETIME,
  recorder_id BIGINT,
  recorder_name VARCHAR(60),
  remark VARCHAR(500),
  created_by BIGINT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);
