-- H2 测试库补建首页汇总接口（/api/oa/portal/summary）依赖但缺失的表，
-- 使 OaPortalControllerTest 可在干净环境下运行（主库定义见 V6/V7/V102 等）。

CREATE TABLE IF NOT EXISTS oa_notice (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  title VARCHAR(200) DEFAULT NULL,
  content VARCHAR(4000) DEFAULT NULL,
  publisher_name VARCHAR(64) DEFAULT NULL,
  publish_time DATETIME DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oa_approval (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  approval_type VARCHAR(64) DEFAULT NULL,
  title VARCHAR(200) DEFAULT NULL,
  applicant_id BIGINT DEFAULT NULL,
  applicant_name VARCHAR(64) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  form_data VARCHAR(4000) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oa_document (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  name VARCHAR(200) DEFAULT NULL,
  folder VARCHAR(200) DEFAULT NULL,
  folder_id BIGINT DEFAULT NULL,
  url VARCHAR(1000) DEFAULT NULL,
  size_bytes BIGINT DEFAULT NULL,
  uploader_id BIGINT DEFAULT NULL,
  uploader_name VARCHAR(64) DEFAULT NULL,
  uploaded_at DATETIME DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oa_suggestion (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  content VARCHAR(2000) DEFAULT NULL,
  proposer_name VARCHAR(64) DEFAULT NULL,
  contact VARCHAR(64) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oa_task (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  title VARCHAR(200) DEFAULT NULL,
  description VARCHAR(2000) DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  priority VARCHAR(32) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  assignee_id BIGINT DEFAULT NULL,
  assignee_name VARCHAR(64) DEFAULT NULL,
  calendar_type VARCHAR(32) DEFAULT NULL,
  plan_category VARCHAR(32) DEFAULT NULL,
  urgency VARCHAR(32) DEFAULT NULL,
  event_color VARCHAR(32) DEFAULT NULL,
  collaborator_ids VARCHAR(1000) DEFAULT NULL,
  collaborator_names VARCHAR(1000) DEFAULT NULL,
  is_recurring TINYINT DEFAULT NULL,
  recurrence_rule VARCHAR(200) DEFAULT NULL,
  recurrence_interval INT DEFAULT NULL,
  recurrence_count INT DEFAULT NULL,
  source_todo_id BIGINT DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oa_work_report (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  title VARCHAR(200) DEFAULT NULL,
  report_type VARCHAR(32) DEFAULT NULL,
  report_date DATE DEFAULT NULL,
  period_start_date DATE DEFAULT NULL,
  period_end_date DATE DEFAULT NULL,
  content_summary VARCHAR(4000) DEFAULT NULL,
  completed_work VARCHAR(4000) DEFAULT NULL,
  risk_issue VARCHAR(2000) DEFAULT NULL,
  next_plan VARCHAR(2000) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  reporter_id BIGINT DEFAULT NULL,
  reporter_name VARCHAR(64) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS attendance_record (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  staff_id BIGINT DEFAULT NULL,
  work_date DATE DEFAULT NULL,
  check_in_time DATETIME DEFAULT NULL,
  check_out_time DATETIME DEFAULT NULL,
  outing_start_time DATETIME DEFAULT NULL,
  outing_end_time DATETIME DEFAULT NULL,
  lunch_break_start_time DATETIME DEFAULT NULL,
  lunch_break_end_time DATETIME DEFAULT NULL,
  outing_minutes INT DEFAULT NULL,
  reviewed TINYINT DEFAULT NULL,
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at DATETIME DEFAULT NULL,
  review_remark VARCHAR(500) DEFAULT NULL,
  note VARCHAR(500) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS survey_template (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  template_code VARCHAR(64) DEFAULT NULL,
  template_name VARCHAR(200) DEFAULT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  content CLOB DEFAULT NULL,
  target_type VARCHAR(32) DEFAULT NULL,
  status INT DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  anonymous_flag TINYINT DEFAULT NULL,
  score_enabled TINYINT DEFAULT NULL,
  total_score INT DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS survey_submission (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  template_id BIGINT DEFAULT NULL,
  target_type VARCHAR(32) DEFAULT NULL,
  target_id BIGINT DEFAULT NULL,
  related_staff_id BIGINT DEFAULT NULL,
  submitter_id BIGINT DEFAULT NULL,
  submitter_name VARCHAR(64) DEFAULT NULL,
  submitter_role VARCHAR(32) DEFAULT NULL,
  anonymous_flag TINYINT DEFAULT NULL,
  score_total INT DEFAULT NULL,
  score_effective INT DEFAULT NULL,
  status INT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS material_purchase_order (
  id BIGINT NOT NULL PRIMARY KEY,
  org_id BIGINT DEFAULT NULL,
  order_no VARCHAR(64) DEFAULT NULL,
  warehouse_id BIGINT DEFAULT NULL,
  supplier_id BIGINT DEFAULT NULL,
  order_date DATE DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  total_amount DECIMAL(18,2) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS material_transfer_order (
  id BIGINT NOT NULL PRIMARY KEY,
  org_id BIGINT DEFAULT NULL,
  transfer_no VARCHAR(64) DEFAULT NULL,
  from_warehouse_id BIGINT DEFAULT NULL,
  to_warehouse_id BIGINT DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

-- crm_lead 补齐渠道统计所需列（主库早已存在，H2 精简版遗漏）
ALTER TABLE crm_lead ADD COLUMN IF NOT EXISTS source VARCHAR(64) DEFAULT NULL;

-- 登录审计与安全策略表（登录链路写入/读取，缺失时污染所有依赖登录的集成测试日志）
CREATE TABLE IF NOT EXISTS auth_login_log (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  staff_id BIGINT DEFAULT NULL,
  username VARCHAR(64) DEFAULT NULL,
  login_type VARCHAR(32) DEFAULT NULL,
  result VARCHAR(32) DEFAULT NULL,
  fail_reason VARCHAR(200) DEFAULT NULL,
  ip VARCHAR(64) DEFAULT NULL,
  user_agent VARCHAR(500) DEFAULT NULL,
  request_id VARCHAR(64) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS compliance_security_policy (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT DEFAULT NULL,
  org_id BIGINT DEFAULT NULL,
  two_factor_enabled TINYINT DEFAULT NULL,
  two_factor_roles VARCHAR(500) DEFAULT NULL,
  password_max_days INT DEFAULT NULL,
  login_fail_lock_count INT DEFAULT NULL,
  login_fail_lock_minutes INT DEFAULT NULL,
  session_timeout_minutes INT DEFAULT NULL,
  masking_enabled TINYINT DEFAULT NULL,
  masking_exempt_roles VARCHAR(500) DEFAULT NULL,
  log_retention_days INT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
);
