-- 继续补 H2 测试库落后于主库的列（同 V37 的性质）：
-- bed 停留在 V1__init 的字段集，crm_contract 是 V10 里的精简 stub，
-- 导致 ElderServiceTest 一批用例在 Bed/CrmContract 查询上直接 BadSqlGrammar。

ALTER TABLE bed ADD COLUMN IF NOT EXISTS bed_type VARCHAR(32) DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS occupancy_source VARCHAR(32) DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS occupancy_ref_type VARCHAR(32) DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS occupancy_ref_id BIGINT DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS lock_expires_at DATETIME DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS occupancy_note VARCHAR(255) DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS last_release_reason VARCHAR(255) DEFAULT NULL;
ALTER TABLE bed ADD COLUMN IF NOT EXISTS last_released_at DATETIME DEFAULT NULL;

ALTER TABLE crm_contract ADD COLUMN IF NOT EXISTS contract_status VARCHAR(32) DEFAULT NULL;
ALTER TABLE crm_contract ADD COLUMN IF NOT EXISTS flow_stage VARCHAR(32) DEFAULT NULL;

ALTER TABLE room ADD COLUMN IF NOT EXISTS remark VARCHAR(255) DEFAULT NULL;
