CREATE TABLE IF NOT EXISTS medical_tcm_assessment (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT DEFAULT NULL COMMENT '长者ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '长者姓名',
  assessment_date DATE NOT NULL COMMENT '评估日期',
  assessor_id BIGINT DEFAULT NULL COMMENT '评估人ID',
  assessor_name VARCHAR(64) DEFAULT NULL COMMENT '评估人',
  assessment_scene VARCHAR(16) NOT NULL DEFAULT 'ADMISSION' COMMENT '评估场景 ADMISSION/REASSESSMENT/SPECIAL',
  constitution_primary VARCHAR(32) DEFAULT NULL COMMENT '主导体质',
  constitution_secondary VARCHAR(32) DEFAULT NULL COMMENT '次体质',
  score DECIMAL(8,2) DEFAULT NULL COMMENT '综合分值',
  confidence DECIMAL(8,2) DEFAULT NULL COMMENT '可信度',
  feature_summary VARCHAR(1024) DEFAULT NULL COMMENT '体质特征摘要',
  suggestion_diet VARCHAR(1024) DEFAULT NULL COMMENT '饮食建议',
  suggestion_routine VARCHAR(1024) DEFAULT NULL COMMENT '起居建议',
  suggestion_exercise VARCHAR(1024) DEFAULT NULL COMMENT '运动建议',
  suggestion_emotion VARCHAR(1024) DEFAULT NULL COMMENT '情志建议',
  nursing_tip VARCHAR(1024) DEFAULT NULL COMMENT '护理提示',
  suggestion_points VARCHAR(1024) DEFAULT NULL COMMENT '建议要点',
  questionnaire_json TEXT DEFAULT NULL COMMENT '问卷明细',
  is_reassessment TINYINT NOT NULL DEFAULT 0 COMMENT '是否复评 1是0否',
  family_visible TINYINT NOT NULL DEFAULT 0 COMMENT '是否家属可见 1是0否',
  generate_nursing_task TINYINT NOT NULL DEFAULT 0 COMMENT '是否生成护理提示任务模板',
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态 DRAFT/PUBLISHED',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  KEY idx_tcm_assessment_org_date (org_id, assessment_date),
  KEY idx_tcm_assessment_org_elder (org_id, elder_id),
  KEY idx_tcm_assessment_org_status (org_id, status)
) COMMENT='中医体质评估记录';

CREATE TABLE IF NOT EXISTS medical_cvd_risk_assessment (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT DEFAULT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT DEFAULT NULL COMMENT '长者ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '长者姓名',
  assessment_date DATE NOT NULL COMMENT '评估日期',
  assessor_id BIGINT DEFAULT NULL COMMENT '评估人ID',
  assessor_name VARCHAR(64) DEFAULT NULL COMMENT '评估人',
  risk_level VARCHAR(16) NOT NULL COMMENT '风险等级 LOW/MEDIUM/HIGH/VERY_HIGH',
  key_risk_factors VARCHAR(1024) DEFAULT NULL COMMENT '关键风险因子',
  lifestyle_json TEXT DEFAULT NULL COMMENT '生活方式项JSON',
  factor_json TEXT DEFAULT NULL COMMENT '风险因子项JSON',
  conclusion VARCHAR(1024) DEFAULT NULL COMMENT '风险结论',
  medical_advice VARCHAR(1024) DEFAULT NULL COMMENT '医嘱建议',
  nursing_advice VARCHAR(1024) DEFAULT NULL COMMENT '护理干预建议',
  followup_days INT DEFAULT NULL COMMENT '随访天数',
  need_followup TINYINT NOT NULL DEFAULT 0 COMMENT '是否需要随访',
  generate_inspection_plan TINYINT NOT NULL DEFAULT 0 COMMENT '是否生成巡检计划',
  generate_followup_task TINYINT NOT NULL DEFAULT 0 COMMENT '是否生成医护随访任务',
  suggest_medical_order TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议开立医嘱',
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态 DRAFT/PUBLISHED',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  KEY idx_cvd_assessment_org_date (org_id, assessment_date),
  KEY idx_cvd_assessment_org_elder (org_id, elder_id),
  KEY idx_cvd_assessment_org_risk (org_id, risk_level),
  KEY idx_cvd_assessment_org_status (org_id, status)
) COMMENT='缺血性心血管病风险评估记录';
