ALTER TABLE `oa_document`
  MODIFY COLUMN `name` VARCHAR(255) NOT NULL COMMENT '文件名',
  MODIFY COLUMN `folder` VARCHAR(128) NULL COMMENT '目录',
  MODIFY COLUMN `uploader_name` VARCHAR(64) NULL COMMENT '上传人',
  MODIFY COLUMN `remark` VARCHAR(500) NULL COMMENT '备注';

ALTER TABLE `oa_document_folder`
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '目录名称',
  MODIFY COLUMN `remark` VARCHAR(500) NULL COMMENT '备注';
