CREATE TABLE oa_work_report (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  report_type VARCHAR(16) NOT NULL COMMENT '类型 DAY/WEEK/MONTH/YEAR',
  report_date DATE NOT NULL COMMENT '总结日期',
  period_start_date DATE DEFAULT NULL COMMENT '周期开始日期',
  period_end_date DATE DEFAULT NULL COMMENT '周期结束日期',
  content_summary VARCHAR(1024) DEFAULT NULL COMMENT '工作概述',
  completed_work VARCHAR(2048) DEFAULT NULL COMMENT '已完成工作',
  risk_issue VARCHAR(1024) DEFAULT NULL COMMENT '问题与风险',
  next_plan VARCHAR(1024) DEFAULT NULL COMMENT '下一步计划',
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态 DRAFT/SUBMITTED',
  reporter_id BIGINT DEFAULT NULL COMMENT '总结人ID',
  reporter_name VARCHAR(64) DEFAULT NULL COMMENT '总结人姓名',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_oa_work_report_org_type_date (org_id, report_type, report_date),
  KEY idx_oa_work_report_org_status (org_id, status),
  KEY idx_oa_work_report_org_reporter (org_id, reporter_id)
) COMMENT='工作总结';
