CREATE TABLE IF NOT EXISTS family_recharge_order (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  family_user_id BIGINT NOT NULL COMMENT '家属用户ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  out_trade_no VARCHAR(64) NOT NULL COMMENT '商户订单号',
  channel VARCHAR(24) NOT NULL DEFAULT 'WECHAT_JSAPI' COMMENT '支付渠道',
  status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT '订单状态 INIT/PREPAY_CREATED/PAID/CLOSED/FAILED',
  amount DECIMAL(12,2) NOT NULL COMMENT '充值金额（元）',
  currency VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  payer_open_id VARCHAR(64) DEFAULT NULL COMMENT '付款人openId',
  prepay_id VARCHAR(128) DEFAULT NULL COMMENT '微信预支付ID',
  wx_transaction_id VARCHAR(128) DEFAULT NULL COMMENT '微信支付单号',
  paid_at DATETIME DEFAULT NULL COMMENT '支付成功时间',
  notify_payload LONGTEXT DEFAULT NULL COMMENT '回调原始报文',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  UNIQUE KEY uk_family_recharge_order_trade_no (out_trade_no),
  KEY idx_family_recharge_order_family (org_id, family_user_id, elder_id, create_time),
  KEY idx_family_recharge_order_status (status, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家属端充值订单';
