CREATE TABLE IF NOT EXISTS family_sms_code_log (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  family_user_id BIGINT DEFAULT NULL COMMENT '家属用户ID',
  phone VARCHAR(20) NOT NULL COMMENT '手机号',
  scene VARCHAR(24) NOT NULL DEFAULT 'LOGIN' COMMENT '验证码场景 LOGIN/SECURITY',
  biz_no VARCHAR(64) NOT NULL COMMENT '业务流水号',
  code_hash VARCHAR(128) NOT NULL COMMENT '验证码哈希',
  status VARCHAR(24) NOT NULL DEFAULT 'SENT' COMMENT '状态 SENT/VERIFIED/USED/EXPIRED/FAILED',
  provider VARCHAR(32) NOT NULL DEFAULT 'MOCK' COMMENT '短信通道',
  provider_message_id VARCHAR(128) DEFAULT NULL COMMENT '通道消息ID',
  provider_request LONGTEXT DEFAULT NULL COMMENT '通道请求报文',
  provider_response LONGTEXT DEFAULT NULL COMMENT '通道响应报文',
  verify_attempts INT NOT NULL DEFAULT 0 COMMENT '已校验失败次数',
  max_attempts INT NOT NULL DEFAULT 5 COMMENT '最大失败次数',
  expires_at DATETIME NOT NULL COMMENT '过期时间',
  verified_at DATETIME DEFAULT NULL COMMENT '验证通过时间',
  used_at DATETIME DEFAULT NULL COMMENT '消费时间',
  last_error VARCHAR(255) DEFAULT NULL COMMENT '最后一次错误',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  UNIQUE KEY uk_family_sms_code_biz_no (biz_no),
  KEY idx_family_sms_code_lookup (org_id, phone, scene, status, expires_at),
  KEY idx_family_sms_code_time (org_id, phone, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家属短信验证码日志';
