CREATE TABLE IF NOT EXISTS family_notify_log (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  family_user_id BIGINT NOT NULL COMMENT '家属用户ID',
  elder_id BIGINT DEFAULT NULL COMMENT '关联老人ID',
  event_type VARCHAR(40) NOT NULL COMMENT '事件类型',
  level VARCHAR(16) NOT NULL DEFAULT 'normal' COMMENT '通知级别 normal/warning/urgent',
  title VARCHAR(100) NOT NULL COMMENT '通知标题',
  content VARCHAR(255) NOT NULL COMMENT '通知内容',
  template_id VARCHAR(128) DEFAULT NULL COMMENT '微信模板ID',
  touser_open_id VARCHAR(64) DEFAULT NULL COMMENT '接收人openId',
  page_path VARCHAR(255) DEFAULT NULL COMMENT '跳转页面',
  payload_json LONGTEXT DEFAULT NULL COMMENT '请求报文',
  response_json LONGTEXT DEFAULT NULL COMMENT '响应报文',
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/SUCCESS/FAILED/SKIPPED',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
  max_retry INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  next_retry_at DATETIME DEFAULT NULL COMMENT '下次重试时间',
  last_error VARCHAR(255) DEFAULT NULL COMMENT '最后一次错误',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_family_notify_retry (status, next_retry_at, update_time),
  KEY idx_family_notify_family (org_id, family_user_id, event_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='家属微信通知投递日志';
