CREATE TABLE IF NOT EXISTS hr_staff_service_plan (
  id BIGINT NOT NULL,
  org_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  staff_no VARCHAR(64) DEFAULT NULL,
  staff_name VARCHAR(64) DEFAULT NULL,
  department_id BIGINT DEFAULT NULL,
  department_name VARCHAR(64) DEFAULT NULL,
  breakfast_enabled TINYINT NOT NULL DEFAULT 0,
  breakfast_unit_price DECIMAL(10,2) DEFAULT NULL,
  breakfast_days_per_month INT DEFAULT NULL,
  lunch_enabled TINYINT NOT NULL DEFAULT 0,
  lunch_unit_price DECIMAL(10,2) DEFAULT NULL,
  lunch_days_per_month INT DEFAULT NULL,
  dinner_enabled TINYINT NOT NULL DEFAULT 0,
  dinner_unit_price DECIMAL(10,2) DEFAULT NULL,
  dinner_days_per_month INT DEFAULT NULL,
  live_in_dormitory TINYINT NOT NULL DEFAULT 0,
  dormitory_building VARCHAR(64) DEFAULT NULL,
  dormitory_room_no VARCHAR(64) DEFAULT NULL,
  dormitory_bed_no VARCHAR(64) DEFAULT NULL,
  meter_no VARCHAR(64) DEFAULT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(255) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_hr_staff_service_plan_org_staff (org_id, staff_id),
  KEY idx_hr_staff_service_plan_org_status (org_id, status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工餐费/宿舍服务方案';

CREATE TABLE IF NOT EXISTS hr_staff_monthly_fee_bill (
  id BIGINT NOT NULL,
  org_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  staff_no VARCHAR(64) DEFAULT NULL,
  staff_name VARCHAR(64) DEFAULT NULL,
  department_id BIGINT DEFAULT NULL,
  department_name VARCHAR(64) DEFAULT NULL,
  fee_month VARCHAR(7) NOT NULL,
  fee_type VARCHAR(16) NOT NULL,
  title VARCHAR(128) DEFAULT NULL,
  quantity DECIMAL(10,2) DEFAULT NULL,
  unit_price DECIMAL(10,2) DEFAULT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  finance_sync_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  finance_sync_id BIGINT DEFAULT NULL,
  finance_sync_at DATETIME DEFAULT NULL,
  finance_sync_by BIGINT DEFAULT NULL,
  dormitory_building VARCHAR(64) DEFAULT NULL,
  dormitory_room_no VARCHAR(64) DEFAULT NULL,
  dormitory_bed_no VARCHAR(64) DEFAULT NULL,
  meter_no VARCHAR(64) DEFAULT NULL,
  detail_json TEXT DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_hr_staff_monthly_fee_bill_org_staff_month_type (org_id, staff_id, fee_month, fee_type),
  KEY idx_hr_staff_monthly_fee_bill_org_month_type (org_id, fee_month, fee_type, is_deleted),
  KEY idx_hr_staff_monthly_fee_bill_finance_sync (org_id, finance_sync_status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工月度餐费/电费账单';
