ALTER TABLE oa_activity_plan
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PLAN_PENDING' COMMENT '状态 DRAFT/PLAN_PENDING/APPROVING/APPROVED/EXECUTING/COMPLETED/REJECTED/CANCELLED',
  MODIFY COLUMN content MEDIUMTEXT DEFAULT NULL COMMENT '活动方案详情',
  MODIFY COLUMN remark VARCHAR(1000) DEFAULT NULL COMMENT '备注',
  ADD COLUMN activity_type VARCHAR(64) DEFAULT NULL COMMENT '活动类型' AFTER title,
  ADD COLUMN participant_tags VARCHAR(1000) DEFAULT NULL COMMENT '参与标签JSON' AFTER participant_target,
  ADD COLUMN participant_elder_ids VARCHAR(1000) DEFAULT NULL COMMENT '参与老人ID JSON' AFTER participant_tags,
  ADD COLUMN estimated_count INT DEFAULT NULL COMMENT '预估人数' AFTER participant_elder_ids,
  ADD COLUMN need_medical_staff TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要医护人员' AFTER estimated_count,
  ADD COLUMN risk_level VARCHAR(16) DEFAULT 'LOW' COMMENT '风险等级 LOW/MEDIUM/HIGH' AFTER need_medical_staff,
  ADD COLUMN need_budget TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要费用' AFTER risk_level,
  ADD COLUMN budget_amount DECIMAL(10,2) DEFAULT NULL COMMENT '预算金额' AFTER need_budget,
  ADD COLUMN budget_description VARCHAR(500) DEFAULT NULL COMMENT '费用说明' AFTER budget_amount,
  ADD COLUMN scheme_attachment_name VARCHAR(255) DEFAULT NULL COMMENT '方案附件名称' AFTER budget_description,
  ADD COLUMN scheme_attachment_url VARCHAR(500) DEFAULT NULL COMMENT '方案附件URL' AFTER scheme_attachment_name,
  ADD COLUMN approval_logs_json MEDIUMTEXT DEFAULT NULL COMMENT '审批日志JSON' AFTER scheme_attachment_url,
  ADD COLUMN current_approval_step INT DEFAULT NULL COMMENT '当前审批步骤' AFTER approval_logs_json,
  ADD COLUMN current_approver_role VARCHAR(32) DEFAULT NULL COMMENT '当前审批角色' AFTER current_approval_step,
  ADD COLUMN current_approver_id BIGINT DEFAULT NULL COMMENT '当前审批人ID' AFTER current_approver_role,
  ADD COLUMN current_approver_name VARCHAR(64) DEFAULT NULL COMMENT '当前审批人姓名' AFTER current_approver_id,
  ADD COLUMN submitted_at DATETIME DEFAULT NULL COMMENT '提交方案时间' AFTER current_approver_name,
  ADD COLUMN approved_at DATETIME DEFAULT NULL COMMENT '最终审批通过时间' AFTER submitted_at,
  ADD COLUMN started_at DATETIME DEFAULT NULL COMMENT '执行开始时间' AFTER approved_at,
  ADD COLUMN completed_at DATETIME DEFAULT NULL COMMENT '执行完成时间' AFTER started_at,
  ADD COLUMN sign_in_records_json MEDIUMTEXT DEFAULT NULL COMMENT '签到记录JSON' AFTER completed_at,
  ADD COLUMN actual_count INT DEFAULT NULL COMMENT '实际参与人数' AFTER sign_in_records_json,
  ADD COLUMN photo_urls_json MEDIUMTEXT DEFAULT NULL COMMENT '活动照片JSON' AFTER actual_count,
  ADD COLUMN execution_remark VARCHAR(1000) DEFAULT NULL COMMENT '执行备注' AFTER photo_urls_json,
  ADD COLUMN actual_expense DECIMAL(10,2) DEFAULT NULL COMMENT '实际花费' AFTER execution_remark,
  ADD COLUMN effect_evaluation VARCHAR(16) DEFAULT NULL COMMENT '效果评价 GOOD/NORMAL/BAD' AFTER actual_expense,
  ADD COLUMN elder_feedback VARCHAR(1000) DEFAULT NULL COMMENT '老人反馈' AFTER effect_evaluation,
  ADD COLUMN risk_situation VARCHAR(1000) DEFAULT NULL COMMENT '风险情况' AFTER elder_feedback,
  ADD COLUMN report_content MEDIUMTEXT DEFAULT NULL COMMENT '活动报告' AFTER risk_situation;
