CREATE TABLE IF NOT EXISTS smart_device (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NULL,
  device_code VARCHAR(64) NOT NULL,
  device_name VARCHAR(120) NOT NULL,
  device_type VARCHAR(64) NOT NULL,
  vendor VARCHAR(120) NULL,
  model VARCHAR(120) NULL,
  location VARCHAR(180) NULL,
  protocol VARCHAR(32) NULL,
  bind_status VARCHAR(32) NOT NULL DEFAULT 'BOUND',
  online_status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
  last_heartbeat_at DATETIME NULL,
  last_event_at DATETIME NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_smart_device_org_code (org_id, device_code, is_deleted),
  KEY idx_smart_device_org_type (org_id, device_type, enabled),
  KEY idx_smart_device_elder (org_id, elder_id)
);

CREATE TABLE IF NOT EXISTS smart_device_event (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  device_id BIGINT NULL,
  elder_id BIGINT NULL,
  device_code VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_level VARCHAR(32) NOT NULL DEFAULT 'INFO',
  event_time DATETIME NOT NULL,
  payload_json JSON NULL,
  location VARCHAR(180) NULL,
  handled TINYINT NOT NULL DEFAULT 0,
  generated_alert_id BIGINT NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_smart_event_org_time (org_id, event_time),
  KEY idx_smart_event_device (org_id, device_code, event_time),
  KEY idx_smart_event_elder (org_id, elder_id, event_time),
  KEY idx_smart_event_alert (generated_alert_id)
);

CREATE TABLE IF NOT EXISTS smart_alert (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NULL,
  device_id BIGINT NULL,
  source_event_id BIGINT NULL,
  alert_no VARCHAR(64) NOT NULL,
  alert_type VARCHAR(64) NOT NULL,
  level VARCHAR(32) NOT NULL,
  title VARCHAR(160) NOT NULL,
  content VARCHAR(1000) NULL,
  location VARCHAR(180) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  first_triggered_at DATETIME NOT NULL,
  latest_triggered_at DATETIME NOT NULL,
  acknowledged_by BIGINT NULL,
  acknowledged_at DATETIME NULL,
  resolved_by BIGINT NULL,
  resolved_at DATETIME NULL,
  resolution_note VARCHAR(1000) NULL,
  escalation_count INT NOT NULL DEFAULT 0,
  notify_family TINYINT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_smart_alert_no (alert_no),
  KEY idx_smart_alert_org_status (org_id, status, level),
  KEY idx_smart_alert_elder (org_id, elder_id, status),
  KEY idx_smart_alert_time (org_id, latest_triggered_at)
);
