-- 告警派单闭环：触发→受理→响应→到场→处置→复盘，超时未响应自动升级
CREATE TABLE IF NOT EXISTS smart_alert_dispatch (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  alert_id BIGINT NOT NULL,
  elder_id BIGINT NULL,
  device_id BIGINT NULL,
  rule_id BIGINT NULL,
  level VARCHAR(16) NOT NULL DEFAULT 'HIGH',
  dispatch_status VARCHAR(16) NOT NULL DEFAULT 'TRIGGERED',
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(60) NULL,
  triggered_at DATETIME NULL,
  assigned_at DATETIME NULL,
  responded_at DATETIME NULL,
  onsite_at DATETIME NULL,
  handled_at DATETIME NULL,
  reviewed_at DATETIME NULL,
  response_deadline DATETIME NULL,
  escalation_count INT NOT NULL DEFAULT 0,
  handle_note VARCHAR(1000) NULL,
  review_note VARCHAR(1000) NULL,
  incident_id BIGINT NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_smart_dispatch_alert (alert_id, is_deleted),
  KEY idx_smart_dispatch_status (org_id, dispatch_status, level),
  KEY idx_smart_dispatch_assignee (org_id, assignee_id, dispatch_status),
  KEY idx_smart_dispatch_deadline (dispatch_status, response_deadline)
);
