-- M5 餐饮管理扩展（菜品/点餐/食谱/备餐/送餐）
CREATE TABLE IF NOT EXISTS dining_dish (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  dish_name VARCHAR(128) NOT NULL COMMENT '菜品名称',
  dish_category VARCHAR(64) DEFAULT NULL COMMENT '菜品分类',
  meal_type VARCHAR(16) DEFAULT NULL COMMENT '适用餐次 BREAKFAST/LUNCH/DINNER/SNACK',
  unit_price DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '单价',
  calories INT DEFAULT NULL COMMENT '热量',
  nutrition_info VARCHAR(512) DEFAULT NULL COMMENT '营养信息',
  allergen_tags VARCHAR(255) DEFAULT NULL COMMENT '过敏原标签，逗号分隔',
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_dining_dish_org_name (org_id, dish_name),
  KEY idx_dining_dish_org_status (org_id, status)
) COMMENT='菜品管理';

CREATE TABLE IF NOT EXISTS dining_recipe (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  recipe_name VARCHAR(128) NOT NULL COMMENT '食谱名称',
  meal_type VARCHAR(16) DEFAULT NULL COMMENT '餐次 BREAKFAST/LUNCH/DINNER/SNACK',
  dish_ids VARCHAR(1024) DEFAULT NULL COMMENT '菜品ID集合，逗号分隔',
  dish_names VARCHAR(1024) DEFAULT NULL COMMENT '菜品名称快照',
  plan_date DATE DEFAULT NULL COMMENT '计划日期',
  suitable_crowd VARCHAR(128) DEFAULT NULL COMMENT '适用人群',
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_dining_recipe_org_date (org_id, plan_date),
  KEY idx_dining_recipe_org_status (org_id, status)
) COMMENT='食谱管理';

CREATE TABLE IF NOT EXISTS dining_prep_zone (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  zone_code VARCHAR(32) NOT NULL COMMENT '备餐分区编码',
  zone_name VARCHAR(64) NOT NULL COMMENT '备餐分区名称',
  kitchen_area VARCHAR(128) DEFAULT NULL COMMENT '所属厨房区域',
  capacity INT DEFAULT NULL COMMENT '备餐能力（份/餐）',
  manager_name VARCHAR(64) DEFAULT NULL COMMENT '负责人',
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_dining_prep_zone_org_code (org_id, zone_code),
  KEY idx_dining_prep_zone_org_status (org_id, status)
) COMMENT='分区备餐';

CREATE TABLE IF NOT EXISTS dining_delivery_area (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  area_code VARCHAR(32) NOT NULL COMMENT '送餐区域编码',
  area_name VARCHAR(64) NOT NULL COMMENT '送餐区域名称',
  building_name VARCHAR(64) DEFAULT NULL COMMENT '楼栋',
  floor_no VARCHAR(32) DEFAULT NULL COMMENT '楼层',
  room_scope VARCHAR(255) DEFAULT NULL COMMENT '覆盖房间范围',
  manager_name VARCHAR(64) DEFAULT NULL COMMENT '负责人',
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '状态 ENABLED/DISABLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_dining_delivery_area_org_code (org_id, area_code),
  KEY idx_dining_delivery_area_org_status (org_id, status)
) COMMENT='送餐区域';

CREATE TABLE IF NOT EXISTS dining_meal_order (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  order_no VARCHAR(32) NOT NULL COMMENT '订单号',
  elder_id BIGINT DEFAULT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) DEFAULT NULL COMMENT '老人姓名',
  order_date DATE NOT NULL COMMENT '订餐日期',
  meal_type VARCHAR(16) NOT NULL COMMENT '餐次 BREAKFAST/LUNCH/DINNER/SNACK',
  dish_ids VARCHAR(1024) DEFAULT NULL COMMENT '菜品ID集合，逗号分隔',
  dish_names VARCHAR(1024) NOT NULL COMMENT '菜品名称快照',
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '订单金额',
  prep_zone_id BIGINT DEFAULT NULL COMMENT '备餐分区ID',
  prep_zone_name VARCHAR(64) DEFAULT NULL COMMENT '备餐分区名称',
  delivery_area_id BIGINT DEFAULT NULL COMMENT '送餐区域ID',
  delivery_area_name VARCHAR(64) DEFAULT NULL COMMENT '送餐区域名称',
  status VARCHAR(16) NOT NULL DEFAULT 'CREATED' COMMENT '状态 CREATED/PREPARING/DELIVERING/DELIVERED/CANCELLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  UNIQUE KEY uk_dining_meal_order_org_no (org_id, order_no),
  KEY idx_dining_meal_order_org_date (org_id, order_date),
  KEY idx_dining_meal_order_org_status (org_id, status),
  KEY idx_dining_meal_order_elder (elder_id)
) COMMENT='点餐管理';

CREATE TABLE IF NOT EXISTS dining_delivery_record (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  meal_order_id BIGINT NOT NULL COMMENT '点餐单ID',
  order_no VARCHAR(32) NOT NULL COMMENT '订单号',
  delivery_area_id BIGINT DEFAULT NULL COMMENT '送餐区域ID',
  delivery_area_name VARCHAR(64) DEFAULT NULL COMMENT '送餐区域名称',
  delivered_by BIGINT DEFAULT NULL COMMENT '送餐人ID',
  delivered_by_name VARCHAR(64) DEFAULT NULL COMMENT '送餐人',
  delivered_at DATETIME DEFAULT NULL COMMENT '送达时间',
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/DELIVERED/FAILED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_dining_delivery_record_org_time (org_id, delivered_at),
  KEY idx_dining_delivery_record_order (meal_order_id),
  KEY idx_dining_delivery_record_status (org_id, status)
) COMMENT='送餐记录';
