-- 医嘱（长期/临时；药疗/护理/检查/饮食）
CREATE TABLE IF NOT EXISTS medical_order (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  emr_id BIGINT NULL,
  order_type VARCHAR(16) NOT NULL DEFAULT 'LONG_TERM',
  category VARCHAR(16) NOT NULL DEFAULT 'DRUG',
  content VARCHAR(500) NOT NULL,
  drug_id BIGINT NULL,
  dosage VARCHAR(64) NULL,
  frequency VARCHAR(16) NULL,
  route VARCHAR(32) NULL,
  quantity_per_time INT NULL,
  start_time DATETIME NULL,
  stop_time DATETIME NULL,
  doctor_id BIGINT NULL,
  doctor_name VARCHAR(60) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  priority VARCHAR(16) NULL,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_order_elder (org_id, elder_id, status),
  KEY idx_order_active (org_id, status, order_type)
);
