-- 慢病随访记录（体征值、用药依从性、评估结论、下次随访日期自动排程）
CREATE TABLE IF NOT EXISTS medical_followup_record (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64) NULL,
  followup_date DATE NOT NULL,
  vital_json VARCHAR(1000) NULL,
  health_data_id BIGINT NULL,
  medication_compliance VARCHAR(16) NULL,
  assessment_level VARCHAR(16) NOT NULL DEFAULT 'CONTROLLED',
  assessment VARCHAR(1000) NULL,
  next_followup_date DATE NULL,
  doctor_id BIGINT NULL,
  doctor_name VARCHAR(60) NULL,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_followup_record_plan (org_id, plan_id, followup_date),
  KEY idx_followup_record_elder (org_id, elder_id, followup_date)
);
