-- 120急救事件（发起→呼叫→送医→返回/住院→关闭；预留 IoT SOS 告警关联 alert_id）
CREATE TABLE IF NOT EXISTS medical_emergency_event (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  elder_id BIGINT NOT NULL,
  elder_name VARCHAR(64) NULL,
  alert_id BIGINT NULL,
  event_time DATETIME NOT NULL,
  location VARCHAR(200) NULL,
  symptom VARCHAR(500) NULL,
  call_time DATETIME NULL,
  call_operator_id BIGINT NULL,
  call_operator_name VARCHAR(60) NULL,
  hospital_name VARCHAR(120) NULL,
  escort_name VARCHAR(60) NULL,
  depart_time DATETIME NULL,
  outcome VARCHAR(16) NULL,
  outcome_time DATETIME NULL,
  outcome_note VARCHAR(500) NULL,
  reporter_id BIGINT NULL,
  reporter_name VARCHAR(60) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'INITIATED',
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_emergency_event_elder (org_id, elder_id, event_time),
  KEY idx_emergency_event_status (org_id, status, event_time),
  KEY idx_emergency_event_alert (alert_id)
);
