-- AI 智能排班：排班方案主表 + 人/日/班次明细表
CREATE TABLE IF NOT EXISTS ai_schedule_proposal (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NULL,
  title VARCHAR(150) NOT NULL,
  dept_id BIGINT NULL,
  dept_name VARCHAR(100) NULL,
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,
  shift_codes VARCHAR(500) NULL,
  staff_ids VARCHAR(2000) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  constraint_snapshot_json TEXT NULL,
  score_json VARCHAR(2000) NULL,
  unfilled_count INT NOT NULL DEFAULT 0,
  generated_at DATETIME NULL,
  adopted_at DATETIME NULL,
  adopted_by BIGINT NULL,
  remark VARCHAR(500) NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_ai_sched_proposal_org (org_id, status, is_deleted),
  KEY idx_ai_sched_proposal_range (org_id, date_from, date_to)
);

CREATE TABLE IF NOT EXISTS ai_schedule_proposal_item (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NULL,
  org_id BIGINT NULL,
  proposal_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  staff_name VARCHAR(64) NULL,
  duty_date DATE NOT NULL,
  shift_code VARCHAR(32) NOT NULL,
  start_time DATETIME NULL,
  end_time DATETIME NULL,
  night_shift TINYINT NOT NULL DEFAULT 0,
  manual_adjusted TINYINT NOT NULL DEFAULT 0,
  violation_note VARCHAR(300) NULL,
  schedule_id BIGINT NULL,
  created_by BIGINT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_ai_sched_item_proposal (proposal_id, is_deleted),
  KEY idx_ai_sched_item_staff (org_id, staff_id, duty_date)
);
