-- M4 财务一体化（老人账户/流水/任务扣费/余额预警）
CREATE TABLE IF NOT EXISTS elder_account (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  balance DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '余额',
  credit_limit DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '信用额度',
  warn_threshold DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '余额预警阈值',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  UNIQUE KEY uk_elder_account_elder (elder_id),
  KEY idx_elder_account_org_id (org_id),
  KEY idx_elder_account_tenant_id (tenant_id)
) COMMENT='老人账户';

CREATE TABLE IF NOT EXISTS elder_account_log (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  account_id BIGINT NOT NULL COMMENT '账户ID',
  amount DECIMAL(12,2) NOT NULL COMMENT '变动金额',
  balance_after DECIMAL(12,2) NOT NULL COMMENT '变动后余额',
  direction VARCHAR(8) NOT NULL COMMENT '方向 DEBIT/CREDIT',
  source_type VARCHAR(32) NOT NULL COMMENT '来源 TASK/BILL/ADJUST/REFUND',
  source_id BIGINT DEFAULT NULL COMMENT '来源单据ID',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_elder_account_log_elder (elder_id),
  KEY idx_elder_account_log_account (account_id),
  KEY idx_elder_account_log_org (org_id)
) COMMENT='老人账户流水';

ALTER TABLE care_task_template
  ADD COLUMN charge_amount DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '任务收费金额';

-- M5 生活与健康管理
CREATE TABLE IF NOT EXISTS meal_plan (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  plan_date DATE NOT NULL COMMENT '日期',
  meal_type VARCHAR(16) NOT NULL COMMENT '餐次 BREAKFAST/LUNCH/DINNER/SNACK',
  menu VARCHAR(512) NOT NULL COMMENT '菜单',
  calories INT DEFAULT NULL COMMENT '热量',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_meal_plan_org_date (org_id, plan_date)
) COMMENT='膳食计划';

CREATE TABLE IF NOT EXISTS activity_event (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  title VARCHAR(128) NOT NULL COMMENT '活动名称',
  event_date DATE NOT NULL COMMENT '活动日期',
  start_time DATETIME DEFAULT NULL COMMENT '开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '结束时间',
  location VARCHAR(128) DEFAULT NULL COMMENT '地点',
  organizer VARCHAR(64) DEFAULT NULL COMMENT '组织者',
  content VARCHAR(512) DEFAULT NULL COMMENT '内容',
  status VARCHAR(16) NOT NULL DEFAULT 'PLANNED' COMMENT '状态 PLANNED/DONE/CANCELLED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_activity_event_org_date (org_id, event_date)
) COMMENT='活动管理';

CREATE TABLE IF NOT EXISTS incident_report (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT DEFAULT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) DEFAULT NULL COMMENT '老人姓名',
  reporter_name VARCHAR(64) NOT NULL COMMENT '报告人',
  incident_time DATETIME NOT NULL COMMENT '发生时间',
  incident_type VARCHAR(32) NOT NULL COMMENT '事故类型',
  level VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '等级 NORMAL/MAJOR',
  description VARCHAR(512) NOT NULL COMMENT '事故描述',
  action_taken VARCHAR(512) DEFAULT NULL COMMENT '处理措施',
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '状态 OPEN/CLOSED',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_incident_org_time (org_id, incident_time),
  KEY idx_incident_elder (elder_id)
) COMMENT='事故登记';

CREATE TABLE IF NOT EXISTS health_basic_record (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) DEFAULT NULL COMMENT '老人姓名',
  record_date DATE NOT NULL COMMENT '记录日期',
  height_cm DECIMAL(5,2) DEFAULT NULL COMMENT '身高(cm)',
  weight_kg DECIMAL(5,2) DEFAULT NULL COMMENT '体重(kg)',
  bmi DECIMAL(5,2) DEFAULT NULL COMMENT 'BMI',
  blood_pressure VARCHAR(16) DEFAULT NULL COMMENT '血压',
  heart_rate INT DEFAULT NULL COMMENT '心率',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_basic_org_date (org_id, record_date),
  KEY idx_health_basic_elder (elder_id)
) COMMENT='基础健康记录';

-- OA 模块
CREATE TABLE IF NOT EXISTS oa_notice (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  content VARCHAR(2048) NOT NULL COMMENT '内容',
  publisher_name VARCHAR(64) DEFAULT NULL COMMENT '发布人',
  publish_time DATETIME DEFAULT NULL COMMENT '发布时间',
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态 DRAFT/PUBLISHED',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_notice_org_time (org_id, publish_time)
) COMMENT='公告';

CREATE TABLE IF NOT EXISTS oa_todo (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  title VARCHAR(128) NOT NULL COMMENT '待办标题',
  content VARCHAR(512) DEFAULT NULL COMMENT '内容',
  due_time DATETIME DEFAULT NULL COMMENT '截止时间',
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '状态 OPEN/DONE',
  assignee_id BIGINT DEFAULT NULL COMMENT '负责人ID',
  assignee_name VARCHAR(64) DEFAULT NULL COMMENT '负责人姓名',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_todo_org_status (org_id, status)
) COMMENT='待办';

CREATE TABLE IF NOT EXISTS oa_approval (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  approval_type VARCHAR(32) NOT NULL COMMENT '类型 LEAVE/REIMBURSE/PURCHASE',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  applicant_id BIGINT DEFAULT NULL COMMENT '申请人ID',
  applicant_name VARCHAR(64) NOT NULL COMMENT '申请人姓名',
  amount DECIMAL(12,2) DEFAULT NULL COMMENT '金额',
  start_time DATETIME DEFAULT NULL COMMENT '开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '结束时间',
  form_data VARCHAR(2048) DEFAULT NULL COMMENT '表单数据(JSON)',
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/APPROVED/REJECTED',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_approval_org_status (org_id, status)
) COMMENT='审批单';

CREATE TABLE IF NOT EXISTS oa_document (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  name VARCHAR(255) NOT NULL COMMENT '文件名',
  folder VARCHAR(128) DEFAULT NULL COMMENT '目录',
  url VARCHAR(512) DEFAULT NULL COMMENT '存储地址',
  size_bytes BIGINT DEFAULT NULL COMMENT '大小',
  uploader_id BIGINT DEFAULT NULL COMMENT '上传人ID',
  uploader_name VARCHAR(64) DEFAULT NULL COMMENT '上传人姓名',
  uploaded_at DATETIME DEFAULT NULL COMMENT '上传时间',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_document_org_folder (org_id, folder)
) COMMENT='文档管理';

CREATE TABLE IF NOT EXISTS oa_task (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  title VARCHAR(128) NOT NULL COMMENT '任务标题',
  description VARCHAR(512) DEFAULT NULL COMMENT '描述',
  start_time DATETIME DEFAULT NULL COMMENT '开始时间',
  end_time DATETIME DEFAULT NULL COMMENT '结束时间',
  priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '优先级 LOW/NORMAL/HIGH',
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '状态 OPEN/DONE',
  assignee_id BIGINT DEFAULT NULL COMMENT '负责人ID',
  assignee_name VARCHAR(64) DEFAULT NULL COMMENT '负责人姓名',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_oa_task_org_time (org_id, start_time),
  KEY idx_oa_task_org_status (org_id, status)
) COMMENT='日程与任务';
