-- 健康服务模块：用药服务、健康管理、健康巡检、护理日志

CREATE TABLE health_drug_dictionary (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  drug_code VARCHAR(64) DEFAULT NULL COMMENT '药品编码',
  drug_name VARCHAR(128) NOT NULL COMMENT '药品名称',
  specification VARCHAR(128) DEFAULT NULL COMMENT '规格',
  unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
  manufacturer VARCHAR(128) DEFAULT NULL COMMENT '生产厂家',
  category VARCHAR(64) DEFAULT NULL COMMENT '分类',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_drug_org_name (org_id, drug_name),
  KEY idx_health_drug_org_code (org_id, drug_code)
) COMMENT='药品字典';

CREATE TABLE health_medication_deposit (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  drug_id BIGINT DEFAULT NULL COMMENT '药品ID',
  drug_name VARCHAR(128) NOT NULL COMMENT '药品名称',
  deposit_date DATE NOT NULL COMMENT '缴存日期',
  quantity DECIMAL(12,2) NOT NULL COMMENT '缴存数量',
  unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
  expire_date DATE DEFAULT NULL COMMENT '到期日',
  depositor_name VARCHAR(64) DEFAULT NULL COMMENT '缴存人',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_med_deposit_org_elder_date (org_id, elder_id, deposit_date),
  KEY idx_health_med_deposit_org_drug (org_id, drug_name)
) COMMENT='药品缴存';

CREATE TABLE health_medication_setting (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  drug_id BIGINT DEFAULT NULL COMMENT '药品ID',
  drug_name VARCHAR(128) NOT NULL COMMENT '药品名称',
  dosage VARCHAR(64) DEFAULT NULL COMMENT '每次剂量描述',
  frequency VARCHAR(64) DEFAULT NULL COMMENT '频次',
  medication_time VARCHAR(128) DEFAULT NULL COMMENT '用药时段描述',
  start_date DATE DEFAULT NULL COMMENT '开始日期',
  end_date DATE DEFAULT NULL COMMENT '结束日期',
  min_remain_qty DECIMAL(12,2) DEFAULT NULL COMMENT '最小剩余阈值',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_med_setting_org_elder (org_id, elder_id),
  KEY idx_health_med_setting_org_drug (org_id, drug_name)
) COMMENT='用药设置';

CREATE TABLE health_medication_registration (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  drug_id BIGINT DEFAULT NULL COMMENT '药品ID',
  drug_name VARCHAR(128) NOT NULL COMMENT '药品名称',
  register_time DATETIME NOT NULL COMMENT '登记时间',
  dosage_taken DECIMAL(12,2) NOT NULL COMMENT '用药量',
  unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
  nurse_name VARCHAR(64) DEFAULT NULL COMMENT '登记护士',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_med_reg_org_elder_time (org_id, elder_id, register_time),
  KEY idx_health_med_reg_org_drug (org_id, drug_name)
) COMMENT='用药登记';

CREATE TABLE health_archive (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  blood_type VARCHAR(16) DEFAULT NULL COMMENT '血型',
  allergy_history VARCHAR(500) DEFAULT NULL COMMENT '过敏史',
  chronic_disease VARCHAR(500) DEFAULT NULL COMMENT '慢病史',
  medical_history VARCHAR(500) DEFAULT NULL COMMENT '既往病史',
  emergency_contact VARCHAR(64) DEFAULT NULL COMMENT '紧急联系人',
  emergency_phone VARCHAR(32) DEFAULT NULL COMMENT '紧急联系电话',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_archive_org_elder (org_id, elder_id)
) COMMENT='健康档案';

CREATE TABLE health_data_record (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  data_type VARCHAR(64) NOT NULL COMMENT '数据类型',
  data_value VARCHAR(256) NOT NULL COMMENT '数据值',
  measured_at DATETIME NOT NULL COMMENT '测量时间',
  source VARCHAR(64) DEFAULT NULL COMMENT '来源',
  abnormal_flag TINYINT NOT NULL DEFAULT 0 COMMENT '异常标记 0否 1是',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_data_org_elder_time (org_id, elder_id, measured_at),
  KEY idx_health_data_org_type (org_id, data_type)
) COMMENT='健康数据';

CREATE TABLE health_inspection (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  inspection_date DATE NOT NULL COMMENT '巡检日期',
  inspection_item VARCHAR(128) NOT NULL COMMENT '巡检项目',
  result VARCHAR(500) DEFAULT NULL COMMENT '巡检结果',
  status VARCHAR(32) DEFAULT NULL COMMENT '状态',
  inspector_name VARCHAR(64) DEFAULT NULL COMMENT '巡检人',
  follow_up_action VARCHAR(500) DEFAULT NULL COMMENT '跟进措施',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_inspection_org_elder_date (org_id, elder_id, inspection_date),
  KEY idx_health_inspection_org_status (org_id, status)
) COMMENT='健康巡检';

CREATE TABLE health_nursing_log (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  source_inspection_id BIGINT DEFAULT NULL COMMENT '来源巡检ID',
  log_time DATETIME NOT NULL COMMENT '日志时间',
  log_type VARCHAR(64) NOT NULL COMMENT '日志类型',
  content VARCHAR(1000) NOT NULL COMMENT '日志内容',
  staff_name VARCHAR(64) DEFAULT NULL COMMENT '记录人',
  status VARCHAR(32) DEFAULT NULL COMMENT '状态',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  KEY idx_health_nursing_log_org_elder_time (org_id, elder_id, log_time),
  KEY idx_health_nursing_log_org_type (org_id, log_type),
  KEY idx_health_nursing_log_org_source_inspection (org_id, source_inspection_id)
) COMMENT='护理日志';

CREATE TABLE health_medication_task (
  id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
  tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
  org_id BIGINT NOT NULL COMMENT '机构ID',
  setting_id BIGINT NOT NULL COMMENT '用药设置ID',
  elder_id BIGINT NOT NULL COMMENT '老人ID',
  elder_name VARCHAR(64) NOT NULL COMMENT '老人姓名',
  drug_id BIGINT DEFAULT NULL COMMENT '药品ID',
  drug_name VARCHAR(128) NOT NULL COMMENT '药品名称',
  planned_time DATETIME NOT NULL COMMENT '计划执行时间',
  task_date DATE NOT NULL COMMENT '任务日期',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING/DONE/SKIPPED',
  registration_id BIGINT DEFAULT NULL COMMENT '完成登记ID',
  done_time DATETIME DEFAULT NULL COMMENT '完成时间',
  remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  created_by BIGINT DEFAULT NULL COMMENT '创建人',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否 1是',
  UNIQUE KEY uk_health_med_task_org_setting_time (org_id, setting_id, planned_time),
  KEY idx_health_med_task_org_elder_date (org_id, elder_id, task_date),
  KEY idx_health_med_task_org_status (org_id, status),
  KEY idx_health_med_task_org_drug (org_id, drug_name)
) COMMENT='待执行用药任务';
